before_install:
  - rvm use 2.1.0 --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - ruby --version
  - rvm --version
  - gem --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq tmux zsh git
language: go
go:
  - 1.2
install:
  - script/cached-bundle install --deployment --without development --jobs 3 --retry 3
script:
  - make
  - make hub
  - script/ruby-test
notifications:
  email: false
env:
  global:
    - TRAVIS_RUBY_VERSION=2.1.0-gh
    - AMAZON_S3_BUCKET=ci-cache
    - AMAZON_ACCESS_KEY_ID=AKIAJQCVTDEWQHRPBPGQ
    - secure: "XAZv5xyNjWt7F9hG0MZhDANVJ5h/ajEZvfJOEIZRQlE3X5x6oVgI8blLh/MmlRSF0kIyLckcn6t2ccjSOvwN2hca5bwZSjIqoKbJyNe2cmkxfi2432vEOu3Ve6PT5hZWX4R5RgT+xWyMjIJcdF3gUMP7ErXl64aEncBzeW6OoXM="
