before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq tmux zsh git
script: script/test
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
notifications:
  email:
    recipients:
      - mislav.marohnic@gmail.com
    on_success: never
