sudo: false
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - script/bootstrap
  - export PATH=~/bin:"$PATH"
language: go
go:
  - 1.4
script: script/test
install: bundle install --path "$HOME/build/$TRAVIS_REPO_SLUG/vendor/bundle" --without development --deployment --jobs=3 --retry=3
cache:
  directories:
    - vendor/bundle
notifications:
  email: false
