sudo: false
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - export PATH=~/bin:"$PATH"
language: go
go:
  - 1.8.x
  - 1.9.x
script: make test-all
install: script/bootstrap
after_success: script/publish-release
env:
  global:
    - AMAZON_S3_BUCKET=ci-cache
    - AMAZON_ACCESS_KEY_ID=AKIAJQCVTDEWQHRPBPGQ
    - secure: "XAZv5xyNjWt7F9hG0MZhDANVJ5h/ajEZvfJOEIZRQlE3X5x6oVgI8blLh/MmlRSF0kIyLckcn6t2ccjSOvwN2hca5bwZSjIqoKbJyNe2cmkxfi2432vEOu3Ve6PT5hZWX4R5RgT+xWyMjIJcdF3gUMP7ErXl64aEncBzeW6OoXM="
    - secure: "eroPaeI0ohBaUjuc/y22VgyN+GDHeWXPIMAZTvSkNZfwL+Oxy861aeawi0zQeduEYon3fSfMBbOxJbrA+6IMU0W+DlR7TTBJ9dbGmeTFCu6ypJRJJtaE5/Kn9PwKjyG6XiPR/YR6818Jiv6yVCLQspjFbhCuKeFoHcu7RAmazKE="
